name: Check the source code
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Prettier
        run: pnpm run format:fix

      - name: Lint
        run: pnpm run lint:fix

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto format
